//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipiesModelNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendGridMail
    {
        public string Sg_event_id { get; set; }
        public string Event { get; set; }
        public string Sg_message_id { get; set; }
        public string Id { get; set; }
        public Nullable<long> Timestamp { get; set; }
        public string Smtp_id { get; set; }
        public string Email { get; set; }
        public string Uid { get; set; }
        public int PrimaryKey { get; set; }
        public string UserAgent { get; set; }
        public string Url { get; set; }
        public string Reason { get; set; }
        public string Type { get; set; }
        public string Guid { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedByUser { get; set; }
    }
}
